[uwsgi]
chdir = /Users/bylba4ka/django_form_handler
module = django_form_handler.wsgi:application

master = true
processes = 5

socket = project.sock
chmod-socket = 660
vacuum = true

die-on-term = true