[uwsgi]

chdir = /home/xdxd1488/django_form_handler
module = django_form_handler.wsgi:application

master = true
processes = 5
threads = 2

socket = /run/uwsgi/project.sock
chmod-socket = 666
vacuum = true

die-on-term = true

pythonpath = /home/xdxd1488/django_form_handler

uid = www-data
gid = www-data

logto = /home/xdxd1488/django_form_handler/logs/uwsgi.log